const card=(title,body,visual,example,question,options,answer,hint)=>({title,body,visual,example,question,options,answer,hint});
export const lessons={
 basics:[
 card('What the business owns. What it owes.','Assets are useful resources. Liabilities are obligations. Equity is the owner’s remaining claim.','balance','Assets $18,000 = Liabilities $7,000 + Equity $11,000','Equipment the business owns is a…',['Asset','Liability','Expense'],0,'Equipment can provide future benefits.'),
 card('A snapshot or a story?','A balance sheet is a snapshot at a specific date. An income statement tells the earnings story over a period.','statements','September 30: balance sheet. September 1–30: income statement.','Which report shows revenues and expenses?',['Balance sheet','Income statement','Statement of owner’s equity'],1,'Think about which statement calculates profit.'),
 card('Earned does not always mean collected.','Performing the service earns revenue. If the customer has not paid, Accounts Receivable records what they owe. These record two aspects of the same amount.','receivable','Work worth $800 → Revenue $800 and Accounts Receivable $800. Earnings are $800, not $1,600.','How much was earned from this service?',['$800','$1,600','$0 until cash arrives'],0,'The receivable is the right to collect the earnings, not additional earnings.'),
 card('Personal withdrawals are not expenses.','Expenses are costs incurred to earn business revenue. An owner’s personal withdrawal reduces equity directly.','equity','Revenue $5,000 − Expenses $2,000 = Net income $3,000. A $700 withdrawal does not change that net income.','What does a withdrawal reduce?',['Net income only','Equity, but not net income','Revenue'],1,'Keep personal distributions out of the income statement.')],
 transactions:[
 card('Read it in two passes.','First name the exact accounts that change. Then translate the changes into assets, liabilities, and equity.','movement','Buying $600 of supplies for cash: Supplies ↑ $600; Cash ↓ $600.','What happens to total assets?',['Increase $600','Decrease $600','No net change'],2,'Both supplies and cash are assets; their changes cancel.'),
 card('Bill once. Collect once. Earn once.','When work is done, debit Accounts Receivable and credit Revenue. When cash arrives later, replace the receivable with cash.','receivable','Bill $900: Accounts Receivable ↑ and Revenue ↑. Collect $900 later: Cash ↑ and Accounts Receivable ↓.','Does collecting the old bill create more revenue?',['Yes, another $900','No, it only collects what was earned','Only if paid next month'],1,'The revenue was already earned when the work was performed.'),
 card('A customer advance is a promise.','When cash arrives before the work, the business owes a service. That obligation is Unearned Revenue, a liability.','advance','Receive $1,200: Cash ↑ and Unearned Revenue ↑. Perform the work later: Unearned Revenue ↓ and Revenue ↑.','When does the advance become revenue?',['When the cash arrives','When the work is performed','When it is deposited in a bank'],1,'Revenue follows the work, not just the cash.'),
 card('Incurred now. Paid later.','A utility cost belongs in the current period when it is incurred, even if the bill will be paid next month.','unpaid','Utilities Expense ↑ $250; Accounts Payable ↑ $250. Cash stays unchanged.','What is the overall effect?',['Assets decrease; equity decreases','Liabilities increase; equity decreases','Assets increase; equity increases'],1,'The liability grows, while expense reduces equity.')],
 operations:[
 card('One pattern. Five accounts.','Start with the opening balance, add what increases it, and subtract what decreases it. What remains is the ending balance.','roll','Beginning + Increases − Decreases = Ending','Which position represents what remains?',['Beginning','Increases','Ending'],2,'The ending balance is the result after this period’s activity.'),
 card('Supplies purchased versus supplies used.','Buying supplies increases the asset. Using supplies reduces the asset and creates an expense.','supplies','Beginning $2,000 + Purchases $5,000 − Used $4,000 = Ending $3,000','If beginning supplies is missing, what is the setup?',['Ending − Purchases + Used','Ending + Purchases − Used','Purchases − Used − Ending'],0,'Undo the addition of purchases and the subtraction of used supplies.'),
 card('Payables grow with purchases, shrink with payments.','Accounts Payable tracks what the business owes. Purchases on account increase it; payments on account decrease it.','payable','Beginning $14,400 + Purchases $79,700 − Payments = Ending $24,400','Which setup finds payments?',['$24,400 − $14,400 + $79,700','$14,400 + $79,700 − $24,400','$79,700 − $14,400 − $24,400'],1,'Payments are the amount removed from everything owed to reach the ending balance.'),
 card('Track the account, not just the cash.','Receivables grow when customers are billed and fall when collected. Unearned Revenue grows with advances and falls when work is earned.','roll','Beginning Receivable + Services on account − Collections = Ending Receivable','What decreases Unearned Revenue?',['Receiving another advance','Performing the prepaid services','Billing a new client'],1,'Completing prepaid work removes the obligation to the customer.')],
 equations:[
 card('The equation is your starting point.','Beginning equity plus investments plus net income minus withdrawals equals ending equity. Say each term out loud before moving numbers.','equity','Beginning equity + Investments + Net income − Withdrawals = Ending equity','Which item is subtracted in this original equation?',['Investments','Net income','Withdrawals'],2,'Money taken by the owner reduces what remains in the business.'),
 card('Finding investments: undo everything else.','Start with ending equity. Remove beginning equity and net income. Add withdrawals back because they were subtracted.','investment','Investments = Ending equity − Beginning equity − Net income + Withdrawals','Ending $16,000; beginning $10,000; income $5,000; withdrawals $1,000. Which setup finds investment?',['16,000 − 10,000 − 5,000 + 1,000','16,000 + 10,000 − 5,000 − 1,000','16,000 − 10,000 + 5,000 − 1,000'],0,'Remove the other additions, then undo the subtraction.'),
 card('Finding withdrawals uses a different start.','Add beginning equity, investments, and net income. Subtract ending equity. The difference is what the owner took out.','withdrawal','Withdrawals = Beginning equity + Investments + Net income − Ending equity','Which value is subtracted when finding withdrawals?',['Ending equity','Investments','Beginning equity'],0,'First calculate what equity would be before a withdrawal. Compare it to what remains.'),
 card('Break a longer problem into small steps.','If you are given assets and liabilities, first find equity at each date. Then use those equity balances to find net income. A loss is negative net income.','bridge','Beginning: $30,000 − $10,000 = $20,000. Ending: $38,000 − $12,000 = $26,000. Investment $8,000; withdrawals $1,000.','Net income = $26,000 − $20,000 − $8,000 + $1,000. What is it?',['$1,000 profit','$1,000 loss','$15,000 profit'],1,'Use the signs carefully: 6,000 minus 8,000 plus 1,000 is negative.')],
 debits:[
 card('Debit is left. Credit is right.','Debit and credit name sides. Neither word means increase for every account. The account’s type determines its increase side.','taccount','Assets, Expenses, Withdrawals ↑ with Debits. Liabilities, Capital, Revenue ↑ with Credits.','Cash is an asset. Its increase goes on the…',['Debit side','Credit side'],0,'Assets increase on the left.'),
 card('A decrease uses the opposite side.','Once you know the normal increase side, reverse it for a decrease. Cash normally increases with a debit, so a cash decrease is a credit.','taccount','Cash ↑ Debit; Cash ↓ Credit. Accounts Payable ↑ Credit; Accounts Payable ↓ Debit.','Accounts Payable decreases. Which side?',['Debit','Credit'],0,'Payables are liabilities; their increase side is credit. Now reverse it.'),
 card('Read the whole account name.','The final word often gives the strongest clue. Wages Payable is a liability; Wages Expense is an expense. Unearned Revenue is an important exception: it is a liability.','account-types','Salaries Expense → Expense → Debit. Salaries Payable → Liability → Credit.','What is the normal balance of Wages Payable?',['Debit','Credit'],1,'“Payable” tells you an amount is owed.'),
 card('Balanced does not mean identical.','Each entry’s total debits equal total credits. There may be one debit and two credits; their amounts must still balance.','split','Equipment: Debit $8,000. Cash: Credit $3,000. Accounts Payable: Credit $5,000.','What are total credits in this entry?',['$3,000','$5,000','$8,000'],2,'Add both credit amounts.')],
 statements:[
 card('Start with the income statement.','Add all revenues, subtract all expenses, and label the difference net income or net loss. Leave owner investments and withdrawals out.','income','Revenue $12,000 − Rent $2,000 − Salaries $4,000 = Net income $6,000','Where does this net income go next?',['Into the owner’s equity statement','Into Accounts Payable','Directly into Cash'],0,'Profit increases the owner’s equity; it is not necessarily all cash.'),
 card('Carry profit into ending capital.','The owner’s equity statement connects the opening capital balance to the closing balance using investment, income, and withdrawals.','equity','Beginning $10,000 + Investment $3,000 + Income $6,000 − Withdrawals $2,000 = Ending $17,000','Which capital balance appears on the balance sheet?',['Beginning capital $10,000','Ending capital $17,000','Investments $3,000'],1,'The balance sheet reports the financial position at the end date.'),
 card('The balance sheet must balance.','Assets equal liabilities plus ending equity. Use the ending capital from the owner’s equity statement.','balance','Assets $25,000 = Liabilities $8,000 + Ending equity $17,000','If liabilities are $8,000 and ending equity is $17,000, assets equal…',['$9,000','$17,000','$25,000'],2,'Add the creditors’ claim and the owner’s claim.'),
 card('Cash flow is its own story.','The statement of cash flows tracks cash received and paid. Owner investment is a cash inflow even though it is not revenue. Credit sales can be revenue without current cash.','cashflow','Collect customers $4,000 + Owner investment $3,000 − Pay rent $1,000 = Cash increase $6,000','Which produces revenue without current cash?',['Owner invests cash','Services performed on account','Customer advance for future work'],1,'The work is completed, but payment will come later.')],
 journal:[
 card('Accounts first. Sides second. Amounts third.','Name the accounts, decide whether each rises or falls, and apply its debit/credit rule. Finish by checking equal debit and credit totals.','journal','Owner invests $2,000 → Debit Cash $2,000; Credit Owner Capital $2,000.','Why is Cash debited?',['Cash is an asset increasing','All payments are debits','Capital is decreasing'],0,'Follow the account type and direction.'),
 card('Do not turn collections into new earnings.','Billing for completed work records Revenue. Collecting that same bill later credits Accounts Receivable, not Revenue.','receivable','Collect old $700 bill → Debit Cash $700; Credit Accounts Receivable $700.','Which account is credited when collecting an old receivable?',['Service Revenue','Accounts Receivable','Accounts Payable'],1,'Remove the customer’s existing debt to the business.'),
 card('One purchase. Three entry lines.','Record the full asset cost as a debit. Split the credits between cash paid now and the amount owed later.','split','Equipment $8,000, cash paid $3,000 → Debit Equipment $8,000; Credit Cash $3,000; Credit Accounts Payable $5,000.','What amount goes to Accounts Payable?',['$8,000','$3,000','$5,000'],2,'The payable is the unpaid portion of the cost.'),
 card('Record each revenue separately.','When one bill includes different services, debit the total receivable and credit each revenue account for its own amount.','multi','Consulting $600 + Design $400 → Debit Accounts Receivable $1,000; Credit Consulting Revenue $600; Credit Design Revenue $400.','What is the Accounts Receivable debit?',['$600','$400','$1,000'],2,'The customer owes the sum of both completed services.')]
};
